### ISSUE TITLE
chromiumdriver crashes

### ISSUE THREAD

**Issue by yurividal** [skrobul/switch2dump#4]
Does this still work? Chromiumdriver crashes for me when i try to run this.
```
/var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok': unknown error: Chrome failed to start: exited abnormally (Selenium::WebDriver::Error::UnknownError)
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by skrobul** [comment]
It does for me, make sure that you have chromium and chromedriver installed. 
Also, I have just pushed the dockerized version that you may want to adapt . 

I found out that switch2 has been charging me for gas even when I'm not at home for weeks, so I've built a version that dumps the records into a database on a daily basis.

**Comment by yurividal** [comment]
Ok, i actually got it to work by using this:
```Capybara.register_driver :headless_chrome do |app|
  options.add_argument('--headless')
  options.add_argument('--disable-gpu')
  options.add_argument('--window-size=1280,800')

  driver = Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)

  ### Allow file downloads in Google Chrome when headless!!!
  ### https://bugs.chromium.org/p/chromium/issues/detail?id=696481#c89
  bridge = driver.browser.send(:bridge)

  path = '/session/:session_id/chromium/send_command'
  path[':session_id'] = bridge.session_id

  bridge.http.call(:post, path, cmd: 'Page.setDownloadBehavior',
                                params: {
                                  behavior: 'allow',
                                  downloadPath: '/tmp/downloads'
                                })
  ###

  driver
end

Capybara.default_driver = Capybara.javascript_driver = :headless_chrome
```
Can you point me to the docker version?
The daily database is actually my goal, because i want to plot it in grafana.

**Comment by skrobul** [comment]
@yurividal one more thing to check - you need to have chromedriver which is compatible with your chrome/chromium browser version. Full list available at https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by skrobul** [comment]
> Can you point me to the docker version?

https://github.com/skrobul/switch2dump/blob/master/Dockerfile
the prebuilt image is in https://hub.docker.com/r/skrobul/switch2dump, so theoretically you can just `docker pull skrobul/switch2dump`

> The daily database is actually my goal, because i want to plot it in grafana.
Good stuff, that's exactly what I ended up doing:

![image](https://user-images.githubusercontent.com/183976/100090558-3b76d300-2e4b-11eb-9f3c-339d68fcc528.png)

**Comment by yurividal** [comment]
Thats awesome mate. Thanks. Im gonna have to adapt your dockerfile, to download the arm7 version of chromium (im running it on a Pi).

**Comment by skrobul** [comment]
Cool cool, there is also a chance this will work with non-chromium browser that's available for both platforms but unfortunately, I don't have time to investigate that now. Pull requests are always welcome though ;-)

**Comment by yurividal** [comment]
@skrobul I ended up rewriting this in python, as i am not familiar with ruby and also using influxDB instead of postgre. I've given you the proper credits in the project.  Cheers
https://github.com/yurividal/Switch2-energy

**Comment by skrobul** [comment]
Thank you very much. Just looked at your project, and that dashboard looks amazing!
